substitutions:
  V_SET: "Voltage Setting"             # 0x00
  I_SET: "Current Setting"             # 0x01
  VOUT: "Voltage value display"        # 0x02
  IOUT: "Current value display"        # 0x03
  POWER: "Output power display value"  # 0x04
  UIN: "Input Voltage"                 # 0x05
#  AH_LOW: "Output AH low 16 bits"      # 0x06
#  AH_HIGH: "Output AH high 16 bits"    # 0x07
#  WH_LOW: "Output WH low 16 bits"      # 0x08
#  WH_HIGH: "Output WH high 16 bits"    # 0x09
#  OUT_H: "Open Time Hours"             # 0x0A
#  OUT_M: "Open Time Minutes"           # 0x0B
#  OUT_S: "Open Time Seconds"           # 0x0C
  t_in: "internal Temperature"         # 0x0D
  t_ex: "external Temperature"         # 0x0D   need external Sensor
#  M052: ""                            # 0x52
#  M053: ""                             # 0x53
#  M054: "0x54"
#  M055: "Over power protection value"      # 0x55
#  M056: "0x56"
#  M057: "Maximum output duration—minutes"  # 0x57
#  M058: "0x58"
#  M059: "0x59"
#  M05C: "0x5C"     # Over Temperatur Protect Set     Celsius    R/W#
  
  
  PROTECT: "Protect State"             # 0x10
  normal: "Running"                    # 0
  OVP: "Over Voltage Protected"        # 1
  OCP: "Over Current Protected"        # 2
  OPP: "Over Power Protected"          # 3
  LVP: "Low Voltage Protected"         # 4
  OAH: "Maximum Output CurrentHour"    # 5
  OHP: "Maximum output time"           # 6
  OTP: "Over tempreture Protected"     # 7
  OEP: "OEP"                           # 8
  OWH: "Maximum output WattHours"      # 9
  ICP: "ICP"                           #10

  LOCK: "Key Lock"   # 0x0F
  unlock: "unlock"   #  0
  locked: "locked"   #  1

  

#  CVCC: "0x11"     # Constant voltage and constant current   State R
#  ONOFF: "0x12"
#  baudrate: "0x19" # baudrate                         R/W
#      # 0 = ?
#      # 1 = ?
#      # 2 = ?
#      # 3 = ?
#      # 4 = ?
#      # 5 = ?
#      # 6 = 115200
#  sleep: "0x15"    #  ??
#  model: "0x16"    #  Model
#  # 0x17                 #  Version


  
