substitutions:
  name: "xy6020"
  device_description: "Monitor and control a xy6020 Digital Control Power Supply via UART-TTL"
  
  tx_pin1: GPIO4
  rx_pin1: GPIO2
  baud_rate: "115200"
  
           # values Max - Min
  <<: !include common.yaml
  #V_set_max: "30"
  V_set_min: "24"
  V_set_step: "0.1"
  i_set_max: "10"
  i_set_min: "0.2"
  i_set_step: "0.1"
  u_set_OVP_max: "65"
  u_set_OVP_min: "0"
  i_set_OVP_max: "21"
  i_set_OVP_min: "0"
  i_set_temp_min: "0"
  i_set_temp_max: "95"
  
           # Register
  V_set: "0x00"    # Voltage Setting          Volt    R/W
  i_set: "0x01"    # Current Setting          Ampere  R/W
  VOUT: "0x02"     # Voltage value display    Voltage  R
  IOUT: "0x03"     # Current value display    Ampere   R
  power: "0x04"    # Power in Watt Output     Watt     R
  UIN: "0x05"      # Input Voltage            Voltage  R
  PROTECT: "0x10"  # Protect Status           Status   R  
      # 0 = normal
      # 1 = OVP  Over Voltage Protected
      # 2 = OCP  Over Current Protected
      # 3 = OPP  Over Power Protected
      # 4 = LVP
      # 5 = OAH
      # 6 = OHP
      # 7 = OTP  Over tempreture Protected
      # 8 = OEP
      # 9 = OWH
      #10 = ICP
  ONOFF: "0x12"
  t_in: "0x0D"     # internal temperatur      Celsius  R
  lock: "0x0F"     # Key Lock                         R/W
      # 0 = unlock
      # 1 = lock
  OUT_H: "0x0A"    # Open Time Hours          Hours    R
  OUT_M: "0x0B"    # Open Time Minutes        Minutes  R
  OUT_S: "0x0C"    # Open Time Seconds        Seconds  R
  baudrate: "0x19" # baudrate                         R/W
      # 6 = 115200
  sleep: "0x15"    #  ??
  M050: "0x50"
  M051: "0x51"
  M052: "0x52"
  M053: "0x53"
  M054: "0x54"
  M055: "0x55"
  M056: "0x56"
  M057: "0x57"
  M058: "0x58"
  M059: "0x59"
  M05C: "0x5C"     # Over Temperatur Protect Set     Celsius    R/W
