esphome:
  name: ${name}
  friendly_name: xy6020
  comment: ${device_description}

esp32:
  board: nodemcu-32s

  
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret xykey
ota:
  password: !secret xyota

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.178.38
    gateway: 192.168.178.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xy6020 Fallback Hotspot"
    password: "UEikMwV1wqU8"


captive_portal:

uart:
 - id: uart_bus1
   tx_pin: ${tx_pin1}
   rx_pin: ${rx_pin1}
   baud_rate: ${baud_rate}
   stop_bits: 1
   parity: NONE
   debug:
     direction: BOTH
     dummy_receiver: true

modbus:
  #send_wait_time: 200ms
  uart_id: uart_bus1
  id: mod_bus

modbus_controller:
  - id: sdm
    address: 1
    modbus_id: mod_bus
    #command_throttle: 0ms
    setup_priority: -10
    update_interval: 10s

