text_sensor:
  - platform: modbus_controller
    modbus_controller_id: sdm
    name: baudrate
    id: baudrate_status
    register_type: holding
    address: 0x19
    #register_count: 0
    raw_encode: HEXBYTES
    filters:
      lambda: |-
        if(x == "0006") {
          return {"115200"};  
        } else if(x == "0000") {
          return {"0"};
        } else if(x == "0001") {
          return {"1"};
        } else if(x == "0002") {
          return {"2"};
        } else if(x == "0003") {
          return {"3"};
        } else if(x == "0004") {
          return {"4"};
        } else if(x == "0005") {
          return {"5"};  
        } else {
          return {"Error"};
        }

sensor:
