text_sensor:
  - platform: modbus_controller
    modbus_controller_id: sdm
    name: baudrate
    id: baudrate_status
    register_type: holding
    address: 0x19
    #register_count: 0
    raw_encode: HEXBYTES
    filters:
      lambda: |-
        if(x == "0006") {
          return {"115200"};  
        } else if(x == "0000") {
          return {"0"};
        } else if(x == "0001") {
          return {"1"};
        } else if(x == "0002") {
          return {"2"};
        } else if(x == "0003") {
          return {"3"};
        } else if(x == "0004") {
          return {"4"};
        } else if(x == "0005") {
          return {"5"};  
        } else {
          return {"Error"};
        }

sensor:
  - platform: modbus_controller
    name: "baud"
    address: 0x019
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "baud"
    accuracy_decimals: 2
    #filters:
    # - multiply: 0.01

number:
  - platform: modbus_controller
     modbus_controller_id: sdm
     name: "Baudrate"
     mode: box
     address: 0x19
     unit_of_measurement: "Volt"
     min_value: "0"
     max_value: "6"
     step: 1
     value_type: U_WORD
     #multiply: 100.0
