external_components:
  - source: github://creepystefan/esphome-XY6020

substitutions:
  tx_pin: "GPIO21"
  rx_pin: "GPIO20"
  
esphome:
  name: xy6020

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3 

wifi:
  ssid: forsteramsee
  power_save_mode: none
  ap: {}
  #password: 
  #manual_ip:
  #  static_ip: !secret xy6020_IP
  #  gateway: !secret gateway
  #  subnet: !secret subnet

web_server:
  port: 80

captive_portal:

logger:
  level: DEBUG

packages:
  remote_package:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      yml/button.yaml,
      yml/numbers.yaml,
      yml/switches.yaml,
      yml/text_sensors.yaml,
      yml/sensorcomponent.yaml,
      yml/uart.yaml,
       ]

