esphome:
  name: ${name}
 # friendly_name: xy6020
  comment: ${device_description}

esp32:
  board: nodemcu-32s

#web_server:
#  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xy6020_IP
    gateway: !secret gateway
    subnet: !secret subnet

  ap:
    ssid: "xy6020 Fallback Hotspot"
    password: "UEikMwV1wqU8"

ota:
  password: !secret xyota

api:
  encryption:
    key: !secret xykey
    
logger:
  level: DEBUG

packages:
  remote_package:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      yml/sensors.yaml,
      yml/numbers.yaml,
      yml/switches.yaml,
      yml/text_senssor.yaml,
      yml/uart.yaml,
      yml/substitutions.yaml,
      yml/wifi.yaml,
      ]

captive_portal:

