esphome:
  name: ${name}
  friendly_name: xy6020
  comment: ${device_description}

esp32:
  board: nodemcu-32s

packages:
  remote_package:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      yml/adress.yaml,
      yml/switches.yaml,
      yml/sensors.yaml,
      yml/textsensors.yaml,
      yml/numbers.yaml,
      yml/core.yaml
      ]
