substitutions:
  tx_pin: "GPIO4"
  rx_pin: "GPIO2"
   
esphome:
  name: ${name}
  friendly_name: XY6020
  comment: ${device_description}

esp32:
  board: nodemcu-32s

logger:
  level: DEBUG

packages:
  Batload:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      yml/wifi.yaml,
      yml/uart.yaml,
      yml/switches.yaml,
      batload_pack/sensor_text.yaml,
      batload_pack/number.yaml,
      batload_pack/substitutions.yaml,
      batload_pack/sensor.yaml
        ]
