substitutions:
  esp_name: "xy6020"
  friendly_name: "XY6020"
  esp_version: "32" #32 or 8266
  esp_board: "nodemcu-32s"
  tx_pin: "GPIO4"
  rx_pin: "GPIO2"
  device_description: "Batterie Laden mit Übereinspeisung"
  powermess: !secret powmess
  updateinterval: "15s"
  i_set_temp_min: "0"
  i_set_temp_max: "95"  
  bat_loadvoltage: "28"    # Loadvoltage for Battery
  bat_undervoltage: "23"   # Minimum Bat Voltage 
  bat_holdvoltage: "27.4"  # Voltage to hold Loading

esphome:
  name: ${esp_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}

esp${esp_version}:
  board: ${esp_board}

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xy6020_IP
    gateway: !secret gateway
    subnet: !secret subnet
  ap:
    ssid: "xy6020 Fallback Hotspot"
    password: "UEikMwV1wqU8"

ota:
  password: !secret xyota

api:
  encryption:
    key: !secret xykey

captive_portal:
  
logger:
  level: DEBUG

packages:
  Batload:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      yml/uart.yaml,
      yml/switches.yaml,
      yml/button.yaml,
      yml/text_sensor.yaml,
      batload_pack/number.yaml,
      batload_pack/sensor.yaml,
        ]
