substitutions:
  esp_name: "xy6020"
  friendly_name: "XY6020"
  esp_version: "32" #32 or 8266
  esp_board: "nodemcu-32s"
  tx_pin: "GPIO4"
  rx_pin: "GPIO2"
  #name: "xy6020"
  #device_description: "Batterie Laden mit Übereinspeisung"
  powermess: !secret powmess
  updateinterval: "15s"
  V_set_max: "30"
  V_set_min: "24"
  V_set_step: "0.1"
  i_set_max: "10"
  i_set_min: "0.0"
  i_set_step: "0.1"
  u_set_OVP_max: "65"
  u_set_OVP_min: "0"
  i_set_OVP_max: "21"
  i_set_OVP_min: "0"
  i_set_temp_min: "0"
  i_set_temp_max: "95"  

esphome:
  name: ${esp_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}

esp${esp_version}:
  board: ${esp_board}
  
logger:
  level: DEBUG

packages:
  Batload:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      yml/wifi.yaml,
      yml/uart.yaml,
      yml/switches.yaml,
      yml/button.yaml,
      batload_pack/sensor_text.yaml,
      batload_pack/number.yaml,
      batload_pack/sensor.yaml,
        ]
