substitutions:
  tx_pin: "GPIO4"
  rx_pin: "GPIO2"
  
esphome:
  name: xy6020
  
esp32:
  board: nodemcu-32s

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #manual_ip:
  #  static_ip: !secret xy6020_IP
  #  gateway: !secret gateway
  #  subnet: !secret subnet
  
ota:
  password: !secret xyota

captive_portal:

logger:
  level: DEBUG

uart:
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 115200
  stop_bits: 1
  parity: NONE
  debug:
    direction: BOTH
    dummy_receiver: true

sensor:
  - platform: xy6020
    Output_Voltage_Display:
      name: "Output Voltage"
   
