number:
   - platform: template
     name: "Power In-Out"
     id: powerinout
     optimistic: true
     unit_of_measurement: "Watt"
     min_value: -200
     max_value: 200
     step: 10

sensor:
  - platform: homeassistant
    name: "shellyPower"
    id: shelly_power
    entity_id: sensor.shellypro3em_0cb815fd43b8_total_active_power
    unit_of_measurement: "W"
    accuracy_decimals: 4
    filters:
     - multiply: 1    
  
  - platform: template
    name: "Negative-shelly Output"
    id: negativ_shelly
    lambda: |-
      if (id(powerinout).state <= 0) {
        return id(powerinout).state - id(powerinout).state - id(powerinout).state;
      } else {
        return id(powerinout).state - id(powerinout).state;
      }
    update_interval: 10ms

  - platform: template
    name: "positiv-shelly Output"
    id: positiv_shelly
    lambda: |-
      if (id(powerinout).state >= 0) {
        return id(shelly_power).state;
      } else {
        return id(shelly_power).state - id(shelly_power).state;
      }
    update_interval: 10ms
