number:
  - platform: template
    name: "Power In-Out"
    id: powerinout
    optimistic: true
    unit_of_measurement: "Watt"
    min_value: -200
    max_value: 200
    step: 10

sensor:
  - platform: template
    name: "Power Out"
    lambda: |-
      if (id(powerinout).state >= 0) {
        return id(powerinout).state;
      } else {
        return id(powerinout).state - id(powerinout).state;
      }
    update_interval: 10s

    
  - platform: template
    name: "Power In"
    lambda: |-
      if (id(powerinout).state >= 0) {
        return id(powerinout).state - id(powerinout).state;
      } else {
        return id(powerinout).state;
      }
    update_interval: 10s

  - platform: homeassistant
    name: "Shelly Power"
    id: shelly
    entity_id: sensor.shellypro3em_0cb815fd43b8_total_active_power
