substitutions:
  tx_pin: "GPIO4"
  rx_pin: "GPIO2"
  
esphome:
  name: xy6020
  comment: "Monitor and control a xy6020 Digital Control Power Supply via UART-TTL"

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: !secret xyota

captive_portal:

logger:
  level: DEBUG

#            Packages for Modbus Controller and XY6020 Functions

sensor:
  -platform: xy6020
   output_voltage:
      name: "${name} output voltage"


packages:
  remote_package:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
#      yml/button.yaml,
#      yml/sensors.yaml,
#      yml/numbers.yaml,
#      yml/switches.yaml,
#      yml/text_senssor.yaml,
      yml/uart.yaml,
      Language/german.yaml,
      #Language/english.yaml,
      #yml/test/M1.yaml,
      #yml/test/M2.yaml,
      #yml/test/M3.yaml,
       ]
