substitutions:
  tx_pin: "GPIO4"
  rx_pin: "GPIO2"
  
esphome:
  name: xy6020
  comment: "Monitor and control a xy6020 Digital Control Power Supply via UART-TTL"

#        Entsprechend die Daten Anpassen von dem zu verwendenden ESP 
esp32:
  board: nodemcu-32s

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xy6020_IP
    gateway: !secret gateway
    subnet: !secret subnet
  
  #ap:
  #  ssid: "xy6020 Fallback Hotspot"
  #  password: "UEikMwV1wqU8"


ota:
  password: !secret xyota

#api:
#  encryption:
#    key: !secret xykey

captive_portal:

logger:
  level: DEBUG



uart:
  - id: uart_bus1
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    baud_rate: 115200
    stop_bits: 1
    parity: NONE
    debug:
      direction: BOTH
      dummy_receiver: true

modbus:
  send_wait_time: 1s
  uart_id: uart_bus1
  id: mod_bus

modbus_controller:
  - id: xy6020
    address: 1
    modbus_id: mod_bus
    #command_throttle: 0ms
    setup_priority: -10
    update_interval: 10s

sensor:
  - platform: modbus_controller
    name: "${UIN}"
    address: 0x05
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Volt"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01
