
sensor:
  - platform: homeassistant
    name: "Diamex Verbraucht Sensor von Home Assistant"
    id: power
    entity_id: sensor.diamexpower_sensor
 
 
#entity_id: sensor.     """"   hier die entität von Homeassistant eintragen  """""    _sensor    
