substitutions:
  name: "xy6020"
  device_description: "Monitor and control a xy6020 Digital Control Power Supply via UART-TTL"
  external_components_source: github://creepystefan/esphome-xy6020@main

  tx_pin1: GPIO4
  rx_pin1: GPIO2

esphome:
  name: ${name}
  friendly_name: xy6020
  comment: ${device_description}
  project:
    name: "syssi.esphome-dps"
    version: 1.1.0
  
esp32:
  board: nodemcu-32s
    
external_components:
  - source: ${external_components_source}
    refresh: 0s

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret xykey
ota:
  password: !secret xyota

# web_server:
#  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.178.38
    gateway: 192.168.178.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xy6020 Fallback Hotspot"
    password: "UEikMwV1wqU8"

captive_portal:

uart:
- id: uart_01
  baud_rate: 115200
  tx_pin: ${tx_pin1}
  rx_pin: ${rx_pin1}
  debug:
      direction: BOTH

modbus:
  id: modbus0
  uart_id: uart_01
  send_wait_time: 0ms

xy6020:
  id: xy60200
  modbus_id: modbus0
  update_interval: 5s
  current_resolution: AUTO

binary_sensor:
  - platform: xy6020
    constant_current_mode:
      name: "${name} constant current mode"

sensor:
  - platform: xy6020
    output_voltage:
      name: "${name} output voltage"
    output_current:
      name: "${name} output current"
    output_power:
      name: "${name} output power"
    input_voltage:
      name: "${name} input voltage"
    voltage_setting:
      name: "${name} voltage setting"
    current_setting:
      name: "${name} current setting"
    firmware_version:
      name: "${name} firmware version"
    intern_temp:
      name: "${name} intern temp"
    runtimehours:
      name: "${name} runtime Hours"
    runtimeminutes:
      name: "${name} runtime Minutes"
    runtimeseconds:
      name: "${name} runtime Seconds" 
    run_power_hour:
      name: "${name} W / h" 
    run_current_hour:
      name: "${name} A / h"

    
  humidity:
      name: "${name} output voltage"
      on_value_range: 
        - above: 24.1
          then:
            - switch.turn_on: "${name} key lock"
        - below: 30.0
          then:
            - switch.turn_off: "${name} key lock"
    
text_sensor:
  - platform: xy6020
    protection_status:
      name: "${name} protection status"
    device_model:
      name: "${name} device model"

switch:
  - platform: xy6020
    output:
      name: "${name} output"
    key_lock:
      name: "${name} key lock"

number:
  - platform: xy6020
    voltage_setting:
      name: "${name} voltage setting"
    current_setting:
      name: "${name} current setting"
