esphome:
  name: xy6020-limiter
  friendly_name: xy6020_Limiter

esp8266:
  board: esp8285

logger:
  level: DEBUG

ota:
  password: !secret xyota_tiese

#api:
#  encryption:
#    key: !secret xykey_tiese

captive_portal:

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid_tiese
  password: !secret wifi_password_tiese
  manual_ip:
    static_ip: !secret xy6020_IP_tiese
    gateway: !secret gateway_tiese
    subnet: !secret subnet_tiese

uart:
  - id: uart_bus1
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 115200
    stop_bits: 1
    parity: NONE
    debug:
      direction: BOTH
      dummy_receiver: true

modbus:
  send_wait_time: 1s
  uart_id: uart_bus1
  id: mod_bus

modbus_controller:
  - id: modbus_controll
    address: 1
    modbus_id: mod_bus
    #command_throttle: 0ms
    setup_priority: -10
    update_interval: 10s

interval:
  - interval: 1s
    then:
      - http_request.get:
          url: http://${HichiIP}/cm?cmnd=status%2010 
          verify_ssl: false
          headers:
            Content-Type: application/json
          on_response:
            then:
              - lambda: |-
                  json::parse_json(id(getrequest).get_string(), [](JsonObject root) {
                      id(power3).publish_state(root["StatusSNS"]["SM"]["16_7_0"]);
                      
                  });
http_request:
  useragent: esphome/device
  timeout: 5s
  id: getrequest

switch:
  - platform: modbus_controller
    modbus_controller_id: modbus_controll
    name: "EIN-AUS Schalter"
    id: onoff
    register_type: holding
    address: 0x12
    bitmask: 1
    entity_category: config
    icon: "mdi:toggle-switch"  

sensor:
  - platform: template
    name: "Aktueller Verbrauch"
    id: power3
    unit_of_measurement: "W"

  - platform: modbus_controller
    name: "Eingestellte Spannung"
    address: 0x00
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "V"
    icon: "mdi:water-percent"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01

  - platform: modbus_controller
    name: "Eingestellter Strom"
    address: 0x01
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Ampere"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01
  
  - platform: modbus_controller
    name: "Spannung am Ausgang"
    address: 0x02
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01

  - platform: modbus_controller
    name: "Strom am Ausgang"
    address: 0x03
    register_type: "holding"
    value_type: U_WORD
    device_class: CURRENT
    #unit_of_measurement: "Ampere"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01

  - platform: modbus_controller
    name: Ausgangsleistung
    address: 0x04
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Watt"
    accuracy_decimals: 2
    filters:
     - multiply: 0.1

  - platform: modbus_controller
    name: "Batterie Spannung"
    id: "Batvolt"
    address: 0x05
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Volt"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01

  - platform: modbus_controller
    name: "Temperatur"
    address: 0x0D
    register_type: "holding"
    value_type: U_WORD
    device_class: "TEMPERATURE"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    accuracy_decimals: 2
    filters:
     - multiply: 0.1

number:
   - platform: modbus_controller
     modbus_controller_id: modbus_controll
     name: "Spannung Einstellen"
     mode: box
     address: 0x00
     unit_of_measurement: "Volt"
     min_value: 0
     max_value: 65
     step: 0.01
     value_type: U_WORD
     multiply: 100.0
      
   - platform: modbus_controller
     modbus_controller_id: modbus_controll 
     name: "Strom Einstellen"
     mode: box
     address: 0x01
     unit_of_measurement: "Ampere"
     min_value: 0
     max_value: 20
     step: 0.01
     value_type: U_WORD
     multiply: 100.0
