# in secrets.yaml
# HichiIPsecret: 192.168.178.60
# intervall: in Compile Code
#- http_request.get:
#          url: http://${HichiIP}/cm?cmnd=status%2010
# in yaml Compile Code
#  substitutions:
#     HichiIP: !secret HichiIPsecret
 

substitutions:
  HichiIP: !secret HichiIPsecret
 


wifi:
  ssid: !secret wifi_ssid_tiese
  password: !secret wifi_password_tiese
  manual_ip:
    static_ip: !secret xy6020_IP_tiese
    gateway: !secret gateway_tiese
    subnet: !secret subnet_tiese

logger:
  level: DEBUG

ota:
  password: !secret xyota_tiese

#api:
#  encryption:
#    key: !secret xykey_tiese

web_server:
  port: 9005
  
uart:
  - id: uart_bus1
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 115200
    stop_bits: 1
    parity: NONE
    debug:
      direction: BOTH
      dummy_receiver: true

modbus:
  send_wait_time: 1s
  uart_id: uart_bus1
  id: mod_bus

modbus_controller:
  - id: modbus_controll
    address: 1
    modbus_id: mod_bus
    #command_throttle: 0ms
    setup_priority: -10
    update_interval: 10s

interval:
  - interval: 1s
    then:
      - http_request.get:
          url: http://192.168.178.60/cm?cmnd=status%2010
          verify_ssl: false
          headers:
            Content-Type: application/json
          on_response:
            then:
              - lambda: |-
                  json::parse_json(id(getrequest).get_string(), [](JsonObject root) {
                      id(power3).publish_state(root["StatusSNS"]["SM"]["16_7_0"]);
                      
                  });
http_request:
  useragent: esphome/device
  timeout: 5s
  id: getrequest

captive_portal:
