esphome:
  name: xy6020-limiter
  friendly_name: xy6020_Limiter

esp8266:
  board: esp8285

packages:
  Batload:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      Tiese/core_tiese.yaml,
      Tiese/sensor.yaml,
      
        ]

switch:
  - platform: modbus_controller
    modbus_controller_id: modbus_controll
    name: "EIN-AUS Schalter"
    id: onoff
    register_type: holding
    address: 0x12
    bitmask: 1
    entity_category: config
    icon: "mdi:toggle-switch"  


number:
   - platform: template
     name: "Batterie Volt Limit"
     id: bat_limit
     mode: box
     optimistic: true
     unit_of_measurement: "Volt"
     initial_value: 10.0
     min_value: 0.0
     max_value: 50
     step: 0.1

   - platform: modbus_controller
     modbus_controller_id: modbus_controll
     name: "Spannung Einstellen"
     mode: box
     address: 0x00
     unit_of_measurement: "Volt"
     min_value: 0
     max_value: 65
     step: 0.01
     value_type: U_WORD
     multiply: 100.0
      
   - platform: modbus_controller
     modbus_controller_id: modbus_controll 
     name: "Strom Einstellen"
     mode: box
     address: 0x01
     unit_of_measurement: "Ampere"
     min_value: 0
     max_value: 20
     step: 0.01
     value_type: U_WORD
     multiply: 100.0
