esphome:
  name: xy6020-limiter
  friendly_name: xy6020_Limiter

esp8266:
  board: esp8285

logger:
  level: DEBUG

ota:
  password: !secret xyota_tiese

#api:
#  encryption:
#    key: !secret xykey_tiese

captive_portal:

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid_tiese
  password: !secret wifi_password_tiese
  manual_ip:
    static_ip: !secret xy6020_IP_tiese
    gateway: !secret gateway_tiese
    subnet: !secret subnet_tiese

uart:
  - id: uart_bus1
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 115200
    stop_bits: 1
    parity: NONE
    debug:
      direction: BOTH
      dummy_receiver: true

modbus:
  send_wait_time: 1s
  uart_id: uart_bus1
  id: mod_bus

modbus_controller:
  - id: modbus_controll
    address: 1
    modbus_id: mod_bus
    #command_throttle: 0ms
    setup_priority: -10
    update_interval: 10s


interval:
  - interval: 1s
    then:
      - http_request.get:
          url: http://${ichiIP}/cm?cmnd=status%2010 
          verify_ssl: false
          headers:
            Content-Type: application/json
          on_response:
            then:
              - lambda: |-
                  json::parse_json(id(getrequest).get_string(), [](JsonObject root) {
                      id(power1).publish_state(root["StatusSNS"]["ENERGY"]["POWER"]);
                      id(power2).publish_state(root["StatusSNS"]["POWER"]);
                      id(power3).publish_state(root["ENERGY"]["POWER"]);
                      id(power4).publish_state(root["StatusSNS"]["ENERGY"]["ApparentPower"]);
                      id(power5).publish_state(root["StatusSNS"]["ApparentPower"]);
                      id(power6).publish_state(root["ENERGY"]["ApparentPower"]);
                  });

http_request:
  useragent: esphome/device
  timeout: 5s
  id: getrequest

switch:
  - platform: modbus_controller
    modbus_controller_id: modbus_controll
    name: EIN-AUS Schalter
    id: onoff
    register_type: holding
    address: 0x12
    bitmask: 1
    entity_category: config
    icon: "mdi:toggle-switch"  

sensor:
  - platform: template
    name: power1
    id: power1
    
  - platform: template
    name: power2
    id: power2

  - platform: template
    name: power3
    id: power3

  - platform: template
    name: power4
    id: power4

  - platform: template
    name: power5
    id: power5

  - platform: template
    name: power6
    id: power6

  - platform: modbus_controller
    name: Eingestellte Spannung
    address: 0x00
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "V"
    icon: "mdi:water-percent"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01

  - platform: modbus_controller
    name: Eingestellter Strom
    address: 0x01
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Ampere"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01
  
  - platform: modbus_controller
    name: Spannung am Ausgang
    address: 0x02
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01

  - platform: modbus_controller
    name: Strom am Ausgang
    address: 0x03
    register_type: "holding"
    value_type: U_WORD
    device_class: CURRENT
    #unit_of_measurement: "Ampere"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01

  - platform: modbus_controller
    name: Ausgangsleistung
    address: 0x04
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Watt"
    accuracy_decimals: 2
    filters:
     - multiply: 0.1

  - platform: modbus_controller
    name: Eingangsspannung
    address: 0x05
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Volt"
    accuracy_decimals: 2
    filters:
     - multiply: 0.01
