esphome:
  name: xy6020-limiter
  friendly_name: xy6020_Limiter

esp8266:
  board: esp8285

packages:
  Batload:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      Tiese/core_tiese.yaml,
      Tiese/sensor.yaml,
      Tiese/number.yaml,
      Tiese/switch.yaml,
        ]

