- platform: modbus_controller
    modbus_controller_id: sdm
    name: "CV / CC"
    register_type: holding
    response_size: 4
    address: 0x11
    bitmask: 0
    raw_encode: HEXBYTES
    #raw_encode: NONE
    lambda: |-
      return x;
