interval:
  - interval: 1s
    then:
      - http_request.get:
          url: http://${ShellyIP}/rpc/Shelly.GetStatus
          verify_ssl: false
          headers:
            Content-Type: application/json
          on_response:
            then:
              - lambda: |-
                  json::parse_json(id(getrequest).get_string(), [](JsonObject root) {
                      id(id).publish_state(root["em:0"]["id"]);
                      id(a_voltage).publish_state(root["em:0"]["a_voltage"]);
                      id(b_voltage).publish_state(root["em:0"]["b_voltage"]);
                      id(c_voltage).publish_state(root["em:0"]["c_voltage"]);
                      id(a_freq).publish_state(root["em:0"]["a_freq"]);
                      id(b_freq).publish_state(root["em:0"]["b_freq"]);
                      id(c_freq).publish_state(root["em:0"]["c_freq"]);
                      
                  });

http_request:
  useragent: esphome/device
  timeout: 5s
  id: getrequest

#######      NEED Interval.yaml

sensor:
  - platform: template
    name: ID
    id: id
    
  - platform: template
    name: a_voltage
    id: a_voltage
