sensor:
  - platform: template
    name: power1
    id: power1
    
  - platform: template
    name: power2
    id: power2

  - platform: template
    name: power3
    id: power3

  - platform: template
    name: power4
    id: power4

  - platform: template
    name: power5
    id: power5

  - platform: template
    name: power6
    id: power6
