- platform: modbus_controller
     #modbus_controller_id:
     name: "EIN-AUS Schalter"
     id: onoff
     register_type: holding
     address: 0x12
     bitmask: 1
     entity_category: config
     icon: "mdi:toggle-switch"  
