esphome:
  name: xy6020_Limiter
  #friendly_name: xy6020_Limiter
  comment: "XY6020 0-Watt Limiter"

packages:
  remote_package:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      test/core.yaml,
      test/ICHI_smartmeter.yaml,
      test/sensors.yaml,
      test/switches.yaml,
      Language/german.yaml,
        ]
