substitutions:
  tx_pin: "GPIO1"  
  rx_pin: "GPIO3" 

esphome:
  name: xy6020_Limiter
  #friendly_name: xy6020_Limiter
  comment: "XY6020 0-Watt Limiter"

esp8266:
  board: esp8285

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #manual_ip:
  #  static_ip: !secret xy6020_IP
  #  gateway: !secret gateway
  #  subnet: !secret subnet
  
  #ap:
  #  ssid: "xy6020 Fallback Hotspot"
  #  password: "UEikMwV1wqU8"


ota:
  password: !secret xyota

api:
  encryption:
    key: !secret xykey

captive_portal:

logger:
  level: DEBUG

#            Packages for Modbus Controller and XY6020 Functions
packages:
  remote_package:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      #yml/button.yaml,
      #yml/sensors.yaml,
      #yml/numbers.yaml,
      #yml/switches.yaml,
      #yml/text_senssor.yaml,
      test/uart_wifimodul.yaml,
      #Language/german.yaml,
      #Language/english.yaml,
       ]
